with open(r'C:\Users\LEGION2\Yaji\student_services_portal\src\index.ts', 'w') as f:
    f.write('interface Student {\n')
    f.write('  id: number;\n')
    f.write('  name: string;\n')
    f.write('  email: string;\n')
    f.write('  status: "active" | "inactive";\n')
    f.write('}\n')
    f.write('\n')
    f.write('/**\n')
    f.write(' * Formats a student object into a readable string.\n')
    f.write(' * @param student - The student object to format\n')
    f.write(' * @returns A formatted string representation of the student\n')
    f.write(' */\n')
    f.write('function formatStudent(student: Student): string {\n')
    f.write('  return `${student.id} - ${student.name} (${student.status})`;\n')
    f.write('}\n')
    f.write('\n')
    f.write('// Create a sample student and display the result\n')
    f.write('const sampleStudent: Student = {\n')
    f.write('  id: 1001,\n')
    f.write('  name: "Maria Santos",\n')
    f.write('  email: "maria.santos@university.edu",\n')
    f.write('  status: "active",\n')
    f.write('}\n')
    f.write('\n')
    f.write('console.log("Sample Student:");\n')
    f.write('console.log(formatStudent(sampleStudent));\n')
    f.write('\n')
    f.write('// Compile check: Run with: npx tsc\n')

print('src/index.ts written successfully')